{% set name = "orographic_precipitation" %}
{% set version = "1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d7d15b6f0d3a40f4a5945931919c09e5dc77092591178a1168459e47e3714092

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3
    - pip
  run:
    - python >=3
    - numpy

test:
  imports:
    - orographic_precipitation

about:
  home: https://github.com/rlange2/orographic-precipitation
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Linear Theory of Orographic Precipitation
  description: |
    A Python framework that implements the Linear Theory of
    Orographic Precipitation following Smith & Barstad (2004).
  doc_url: https://github.com/rlange2/orographic-precipitation/blob/master/README.rst
  dev_url: https://github.com/rlange2/orographic-precipitation

extra:
  recipe-maintainers:
    - rlange2
